Fix bug of reset axes rotation after declining calibration loading
LabExT/LabExT pull request #105
Opened 2022-11-16 13:05 UTC by maltewae

2022-11-16 14:50 UTC, marcoep requested changes
Wonderful! Would it make sense to add a unittest which specifically provokes the bug? Obv. in the end, it should pass, but I'm missing a piece of code which tells me what was wrong...

2022-11-30 12:34 UTC, maltewae commented
I would add integration tests in another PR. Then I can test the entire workflow.

The mistake was the following (which was really stupid):
All transformations (Axes Rotation, Single Point and Kabsch) have an `initialize` method. This is used to set up the transformation once and also to reset the transformation. In the calibrations (which manage these transformations) there are the methods `reset_single_point_offset` and `reset_kabsch_rotation`. These reset (as the name suggests) the transformations by calling the `initialize` method and then updating the status of the calibration. These methods are mainly used when a new chip is imported.

Here is the error:
The `initialize` method of the Kabsch rotation previously allowed `axes_rotation: Type[AxesRotation] = None`. If `axes_rotation` was None, a new `AxesRotation` object is created from which the calibration was not informed. Therefore, if the `AxesRotation` of the calibration (other `AxesRotation` object than the one in the `KabschRotation`) was changed, the `KabschRotation` was not informed. This meant that the unit vectors could not be adjusted. This resulted in the going down instead of the going up when lifting.

2022-11-30 14:52 UTC, marcoep approved these changes

2022-11-30 14:52 UTC, marcoep commented
Thank you for the explanation. This is good to merge.

2022-12-01 12:22 UTC, merged