Use blitting in live plot to improve performance
LabExT/LabExT pull request #183
Opened 2023-12-04 06:17 UTC by marcoep

See:
* https://matplotlib.org/stable/api/animation_api.html
* https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.FuncAnimation.html#matplotlib.animation.FuncAnimation
* https://matplotlib.org/stable/users/explain/animations/blitting.html
* https://stackoverflow.com/questions/17558096/animated-title-in-matplotlib/30860027#30860027
* https://stackoverflow.com/questions/14844223/python-matplotlib-blit-to-axes-or-sides-of-the-figure

2023-12-10 14:34 UTC, DJAntivenom requested changes
This is a cool update, however, it doesn't seem to work for me :sweat_smile: 

There are three things:
1. After opening the live viewer and adding a `PowerMeterSimulator` I click 'Start PM'. Then nothing happens and nothing is plotted, but the GUI is still responsive and I have 17 FPS on the empty plotting area. If I then click on 'Update Settings' or 'Stop PM' the whole of LabExT freezes and is completely unresponsive for about 20 seconds. 
2. If I add a `LaserSimulator` and start it, the other buttons work fine and nothing freezes, however, nothing happens on the plot. It just remains empty.
3. In `LabExT.View.LiveViewer.LiveViewerView.ControlFrame.__init__` you use emojis. (This was added in a previous commit, but I must have missed it.) This is a cool idea, however, it is quite dangerous. On my Windows 10 PC I was missing a font and I kid you not, `tkinter` nuked my entire display driver :joy:. It really wasn't built around these kinds of ascii-codes. After installing the required font it worked, but finding that out took quite some time, which I think we shouldn't put our users through XD

2023-12-12 15:32 UTC, boris-vukovic commented
Cool feature, it worked for me. However, I probabely had the emoji font installed. As @DJAntivenom suggested, I would remove it for sake of compatibility.

2023-12-12 16:20 UTC, DJAntivenom approved these changes

2023-12-13 05:46 UTC, marcoep commented
> Cool feature, it worked for me. However, I probabely had the emoji font installed. As @DJAntivenom suggested, I would remove it for sake of compatibility.

Solved in #182 .

2023-12-13 06:09 UTC, merged