SmarAct MCS2 driver for 3D and 6D modules
LabExT/LabExT pull request #228
Opened 2024-09-26 13:00 UTC by ErikMaris

@marcoep

Hi Marco,

Last time we discussed the MCS2 driver, you suggested to share the handle between the different instances of Stage6DSmarActMCS2 via a module-level variable called _OPEN_6D_MCS2_HANDLE. I implemented this--could you please have a look whether I did this correctly?

You also mentioned the following tests; try that:
1. you can instantiate the two LabExT stages (one for ch1-3, one for ch4-6) and connect to both of them at the same time
2. you can individually control them (moving, etc)
3. you can simultaneously control them (i.e. send moving commands to both stages shortly after each other s.t. both stages move simultaneously).

I addressed these points in the Notebook LabExT/Movement/Stages/Stage6DSmarActMCS2_test_functions.ipynb. Luckily, everything works as desired and you can verify this via the printed output.

I am looking forward to hear your feedback!

Best wishes,
Erik

P.S. I mistakenly forked from main, but luckily the branch can still be automatically merged with dev.

2024-09-28 05:07 UTC, marcoep requested changes
Really great job demonstrating how you tested the drivers! Well done!

I have largely two requests: share the `_Channel` class between the drivers and explain better why `open_new_connection` is needed in the 6D class?

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage3DSmarActMCS2.py
> +        return cls.driver_path_dialog.path_has_changed
As far as I understood, this function is not necessary for the MCS2 since you're importing the smaract MCS2 functions in line 17 - without the need to load an uninstallable driver package from config file. 

Please get rid of this function (both driver classes).

In the parent class `Stage` the property `driver_specifiable` is in any case False, so the load_driver method is never called.

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage3DSmarActMCS2.py
> +    driver_path_dialog = None
Please add property `description`, see https://github.com/ErikMaris/LabExT/blob/a54462467635a9538a2131ab275500459a94b6c4/LabExT/Movement/Stage.py#L63

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +    driver_path_dialog = None
same

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +        return cls.driver_path_dialog.path_has_changed
same

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +    class _Channel:
Please do not duplicate code for the _Channel class between files. Refactor this class into a separate file and use it in both the main driver classes.

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage3DSmarActMCS2.py
> +    class _Channel:
Please do not duplicate code for the _Channel class between files. Refactor this class into a separate file and use it in both the main driver classes.

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +            self.open_new_connection = True
What point does this property serve?

I believe in this implementation you assume that a user always initializes _Ch1-3 first and the others second? That might be an issue, because Ch4-6 cannot be used independently if you rely on an open connection from another driver instance.

It would be better if you check if there's an open connection available and if yes attach to that, if no open a new one. I believe that you can rely on the garbage collector to close any open connections (or keep track of open connections yourself and close if last driver is GC-ed).

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage3DSmarActMCS2_test_functions.ipynb
After final approval of this PR, please remove this test file - this does not belong into the main repo. If you want you can move it to the tests folder.

2024-09-28 05:07 UTC, marcoep commented on LabExT/Movement/Stages/Stage6DSmarActMCS2_test_functions.ipynb
After final approval of this PR, please remove this test file - this does not belong into the main repo. If you want you can move it to the tests folder.

2025-03-21 15:27 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage3DSmarActMCS2.py
> +        return cls.driver_path_dialog.path_has_changed
Done

2025-03-21 15:27 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage3DSmarActMCS2.py
> +    driver_path_dialog = None
Done -- also added driver_specifiable = False

2025-03-21 15:27 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +        return cls.driver_path_dialog.path_has_changed
Done

2025-03-21 15:29 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +    class _Channel:
The new ChannelMCS2 class is in the folder Movement/Stages. Should I make Movement/Channels for consistency?

2025-03-21 15:29 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage3DSmarActMCS2.py
> +    class _Channel:
See previous

2025-03-21 15:36 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage3DSmarActMCS2_test_functions.ipynb
Done

2025-03-21 15:36 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage6DSmarActMCS2_test_functions.ipynb
Done

2025-03-21 16:20 UTC, ErikMaris commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +            self.open_new_connection = True
Correct, we assume that the locators with suffixes _Ch1-3 and _Ch4-6 are always connected in this order. Since the list of locators, generated by calling `find_stage_addresses()` is not sorted, this order is retained.

Do I understand correctly that you suggest to use the attribute `self.connected` to check whether an open connection is already available? Unfortunately, we cannot use it to recognise whether a connection has been opened yet, because it is always `self.connected = False` when `Stage6DSmarActMCS2.py` object is instantiated, independently of the other locators.

The purpose of `open_new_connection` is to differentiate between: 
(1) opening a new connection to a new MCS2 module with two bus modules (and assigning the first bus to the object) 
(2) keeping the current connection (in `_OPEN_6D_MCS2_HANDLE`) but assigning the second bus to the object. 
If there would be two MCS2 modules with two busses each, this would be recognised and an error would be thrown. This scenario is not supported, because we only store one global handle in `_OPEN_6D_MCS2_HANDLE` to one MCS2 module.

Or do you mean something like this—removing `open_new_connection` but also the error that checks for the scenario described before (with 2x MCS2 with 2x bus modules each)? 
```
        if _OPEN_6D_MCS2_HANDLE is None:
            _OPEN_6D_MCS2_HANDLE = self._open_system()
            self.handle = _OPEN_6D_MCS2_HANDLE
        else:
            self.handle = _OPEN_6D_MCS2_HANDLE
```

2025-04-17 00:59 UTC, marcoep commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +    class _Channel:
nope, all good as is

2025-04-17 01:20 UTC, marcoep commented on LabExT/Movement/Stages/Stage6DSmarActMCS2.py
> +            self.open_new_connection = True
If you want to be super correct, you could make `_OPEN_6D_MCS2_HANDLE` a dictionary and store the open handles depending on the rest of their USB address...

But your solution here works as well, with a bit more rigorous error checking. Which is good in any  case.

2025-04-17 01:22 UTC, marcoep approved these changes

2025-04-17 02:36 UTC, merged